### PR TITLE
Add kdevelop and kate

### PR DESCRIPTION
**Pull request by juanfra684**

### CODE REVIEW

**Comment by deathtrip** [comment]
i don't think kate needs mprotect off, i got a few denied rwx executions when handling large files, but never a crash

**Comment by juanfra684** [comment]
On Thursday 10 September 2015 03:38:19 deathtrip wrote:
> i don't think kate needs mprotect off, i got a few denied rwx executions
> when handling large files, but never a crash

Kate crashes when I try to edit a small python script (115 lines).

```
open("/usr/share/katepart5/script/indentation/python.js", O_RDONLY|O_CLOEXEC) 
= 27
fcntl(27, F_SETFD, FD_CLOEXEC)          = 0
fstat(27, {st_mode=S_IFREG|0644, st_size=5596, ...}) = 0
fstat(27, {st_mode=S_IFREG|0644, st_size=5596, ...}) = 0
read(27, "var katescript = {\n    \"name\": \""..., 16384) = 5596
read(27, "", 10788)                     = 0
read(27, "", 16384)                     = 0
close(27)                               = 0
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 
0x3258d1ba000
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 
0x32575da2000
mmap(NULL, 8392704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, 
-1, 0) = 0x32552b60000
mprotect(0x32552b60000, 4096, PROT_NONE) = 0
clone(child_stack=0x3255335fef0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|
CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|
CLONE_CHILD_CLEARTID, parent_tidptr=0x325533609d0, tls=0x32553360700, 
child_tidptr=0x325533609d0) = 2222
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 
0x32575d9a000
mmap(NULL, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 
0x325680c9000
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 
0x32575d92000
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 
0x32574042000
mmap(NULL, 2147483648, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|
MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = -1 EPERM (Operation not permitted)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0xbbadbeef} ---
+++ killed by SIGSEGV (core dumped) +++
```

**Comment by deathtrip** [comment]
well... kate now crashes for me with mprotect when displaying a dialog box, as well as dolphin.
maybe the kde team will fix this in some future version, since it seems to affect more apps. For now we should add them.

**Comment by juanfra684** [comment]
In my case, I suspect that the problem is related to the js files used for the indentation. Kate crashes when I press <kbd>enter</kbd> after of a line like this:
```python
def hello:

**Comment by thestinger** [comment]
Applied as 4b892872318d2b49ac9bc6ece85222309dd5b8f8, thanks. These issues all have to do with Qt adopting JavaScript and using a JIT compiler for it by default.

**Pull request closed without merging**
