### PR TITLE
PAX_RANDMMAP needs to be disabled for convert, otherwise convert will…

### PR DESCRIPTION
**Pull request by choopm**
… max out the CPU in an infinite loop. See 'convert pic.png -blur 0x3 picnew.png'

### CODE REVIEW

**Comment by choopm** [comment]
Here's the strace, trimmed to the infinite loop:
---
open("/proc/self/maps", O_RDONLY)       = 9
fstat(9, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x36be3571000
read(9, "00400000-00401000 r-xp 00000000 "..., 1024) = 1024
close(9)                                = 0
munmap(0x36be3571000, 4096)             = 0
mmap(0x200000000, 25769803776, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x365d9162000
munmap(0x365d9162000, 25769803776)      = 0
---
This will repeat forever. Any chance merging this commit?

**Comment by thestinger** [comment]
I'd like to try to duplicate it before adding an exception. It's buggy if it relies on mmap hints being respected so it would be nice to get it fixed.

**Comment by thestinger** [comment]
If it's single-threaded and they are actually checking for gaps (it looks like they are), then it should just be using `MAP_FIXED`.

**Comment by thestinger** [comment]
The grsecurity and PaX patches are no longer public, so paxd maintenance has ended.

**Pull request closed without merging**
